version: "3"
services:
    db:
        image: mongo
        volumes: 
            - ./mongodata:/data
        ports:
            - "27018:27017"
            
    back:
        image: beshlawy38/fitmeback:latest
        ports: 
            - "3001:3001"
        volumes: 
            - ./fitMeBack:/home/node/code
            - /home/node/code/node_modules
            - /home/node/code/.git
        links: 
            - db
        stdin_open: true
        tty: true
        depends_on: 
            - db
        environment: 
            MONGO_CONNECTION_STRING: mongodb://db:27017
    front:
        image: beshlawy38/fitmefront:latest
        ports:
            - "3000:3000"
        volumes: 
             - ./fitMeFront:/home/react/code
             - /home/react/code/node_modules
             - /home/react/code/.git
        links: 
             - back
        stdin_open: true
        tty: true
        depends_on: 
             - back
        environment: 
            BACKEND_CONNECTION: back:3000
            
            
